server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh3 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #微服务名称
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh4
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一队请求头，名称为X-Request-Id，值为1024
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            #- After=2020-11-20T11:23:20.554+08:00[Asia/Shanghai]
            #- Before=2020-11-20T11:26:25.554+08:00[Asia/Shanghai]
            #- Between=2020-11-20T11:29:25.554+08:00[Asia/Shanghai],2020-11-20T11:30:25.554+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id,\d+
            - Host=**.gatewayst.com
            - Method=GET





eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
